In [52]:
import pandas as pd
import re
df_zenodo = pd.read_csv(r'C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_Zenodo\S669.csv', sep=',')

In [53]:
def extract_num(mut_str):
    match = re.search(r'\d+', str(mut_str))
    return int(match.group()) if match else None

# CSV 미리 정리 (매칭 속도 향상)
df_zenodo['WT'] = df_zenodo['PDB_Mut'].str[0]
df_zenodo['MT'] = df_zenodo['PDB_Mut'].str[-1]
df_zenodo['PDB_POS_VAL'] = df_zenodo['PDB_Mut'].apply(extract_num)

In [54]:
df_zenodo.columns

Index(['Protein', 'PDB_Mut', 'Seq_Mut', 'Temperature', 'pH', 'DOI', 'EXPDTA',
       'Resolution', 'WT_PDB', 'Chain', 'INV_PDB', 'Experimental_DDG_dir',
       'ACDC-NN_dir', 'ACDC-NN-Seq_dir', 'DDGun_dir', 'DDGun3D_dir',
       'DUET_dir', 'Dynamut_dir', 'FoldX_dir', 'I-Mutant3.0_dir',
       'I-Mutant3.0-Seq_dir', 'INPS-Seq_dir', 'INPS3D_dir', 'MAESTRO_dir',
       'mCSM_dir', 'MuPro_dir', 'PopMusic_dir', 'PremPS_dir', 'SAAFEC-Seq_dir',
       'SDM_dir', 'ThermoNet_dir', 'Experimental_DDG_inv', 'ACDC-NN_inv',
       'ACDC-NN-Seq_inv', 'DDGun_inv', 'DDGun3D_inv', 'DUET_inv',
       'Dynamut_inv', 'FoldX_inv', 'I-Mutant3.0_inv', 'I-Mutant3.0-Seq_inv',
       'INPS-Seq_inv', 'INPS3D_inv', 'MAESTRO_inv', 'mCSM_inv', 'MuPro_inv',
       'PopMusic_inv', 'PremPS_inv', 'SAAFEC-Seq_inv', 'SDM_inv',
       'ThermoNet_inv', 'WT', 'MT', 'PDB_POS_VAL'],
      dtype='object')

In [55]:
df_zenodo

,Protein,PDB_Mut,Seq_Mut,Temperature,pH,DOI,EXPDTA,Resolution,WT_PDB,Chain,...,mCSM_inv,MuPro_inv,PopMusic_inv,PremPS_inv,SAAFEC-Seq_inv,SDM_inv,ThermoNet_inv,WT,MT,PDB_POS_VAL
0,1a0fA,S11A,S11A,329.83,6.5,10.1042/BJ20061707,X-RAY DIFFRACTION,2.10,1a0f,A,...,-1.904,-0.54484,-0.52,0.63,-0.70,-1.98,-0.1772,S,A,11
1,1a7vA,A104H,A104H,298.15,6.5,10.1016/j.jmb.2009.07.074,X-RAY DIFFRACTION,2.30,1a7v,A,...,0.279,-1.03837,0.43,0.41,-0.59,1.00,-0.0441,A,H,104
2,1a7vA,A66H,A66H,298.15,6.5,10.1016/j.jmb.2009.07.074,X-RAY DIFFRACTION,2.30,1a7v,A,...,0.167,-1.01277,-1.40,0.15,-0.64,-0.21,-0.2933,A,H,66
3,1a7vA,A91H,A91H,298.15,6.5,10.1016/j.jmb.2009.07.074,X-RAY DIFFRACTION,2.30,1a7v,A,...,0.062,-1.01401,0.28,0.44,-0.60,1.00,-0.0203,A,H,91
4,1a7vA,D3H,D3H,298.15,6.5,10.1016/j.jmb.2009.07.074,X-RAY DIFFRACTION,2.30,1a7v,A,...,-0.110,-0.30502,0.03,0.57,-0.44,0.15,-0.1593,D,H,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,5jxbA,D329P,D25P,NaN,7.5,10.1371/journal.pone.0098124,X-RAY DIFFRACTION,2.90,5jxb,A,...,-0.374,-0.34615,-0.53,1.09,-0.94,0.74,-0.0681,D,P,329
665,5oaqA,Y429H,Y199H,298.00,7.4,10.1111/febs.14817,X-RAY DIFFRACTION,1.95,5oaq,A,...,0.352,-0.97128,-0.34,1.86,-0.31,0.24,1.5324,Y,H,429
666,5vp3A,R39K,R39K,298.15,8.0,10.1016/j.saa.2016.01.020,X-RAY DIFFRACTION,2.15,5vp3,A,...,-0.631,-1.18199,-0.56,0.52,-0.45,0.12,-0.7076,R,K,39
667,5vp3A,S128G,S128G,298.15,8.0,10.1016/j.saa.2016.01.020,X-RAY DIFFRACTION,2.15,5vp3,A,...,-1.153,-0.57156,-0.28,-0.03,-0.40,-2.23,-0.1563,S,G,128
668,5vp3A,V183T,V183T,298.15,8.0,10.1016/j.saa.2016.01.020,X-RAY DIFFRACTION,2.15,5vp3,A,...,-0.702,-0.27215,-0.31,1.29,NaN,0.98,-0.0207,V,T,183

In [56]:
df_zenodo = df_zenodo[["Protein",
           "WT",
           "PDB_POS_VAL",
           "MT",
           "Experimental_DDG_dir"]]

In [57]:
df_zenodo["PDB"] = df_zenodo["Protein"].str[:-1]
df_zenodo["Chain"] = df_zenodo["Protein"].str[-1]

C:\Users\Kunny\AppData\Local\Temp\ipykernel_26108\1754108732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_zenodo["PDB"] = df_zenodo["Protein"].str[:-1]
C:\Users\Kunny\AppData\Local\Temp\ipykernel_26108\1754108732.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_zenodo["Chain"] = df_zenodo["Protein"].str[-1]

In [59]:
df_zenodo = df_zenodo.drop(columns=['Protein'])

df_zenodo = df_zenodo.rename(columns={
    "MT": "Mut",
    "PDB_POS_VAL": "MutPos",
    "Experimental_DDG_dir": "DDG",
    "PDB": "PDB_ID"
})

In [63]:
df_zenodo["Key"] = df_zenodo["PDB_ID"] + "_" + df_zenodo["Chain"]

In [64]:
df_zenodo

    WT  MutPos Mut    DDG PDB_ID Chain     Key
0    S      11   A -1.800   1a0f     A  1a0f_A
1    A     104   H -2.690   1a7v     A  1a7v_A
2    A      66   H -1.980   1a7v     A  1a7v_A
3    A      91   H -1.700   1a7v     A  1a7v_A
4    D       3   H -1.360   1a7v     A  1a7v_A
..  ..     ...  ..    ...    ...   ...     ...
664  D     329   P -1.440   5jxb     A  5jxb_A
665  Y     429   H -2.990   5oaq     A  5oaq_A
666  R      39   K  0.413   5vp3     A  5vp3_A
667  S     128   G -0.378   5vp3     A  5vp3_A
668  V     183   T  0.354   5vp3     A  5vp3_A

[669 rows x 7 columns]

In [65]:
df_zenodo.to_csv("S669_zenodo.tsv", sep='\t', index=False)

In [66]:
print(df_zenodo)

    WT  MutPos Mut    DDG PDB_ID Chain     Key
0    S      11   A -1.800   1a0f     A  1a0f_A
1    A     104   H -2.690   1a7v     A  1a7v_A
2    A      66   H -1.980   1a7v     A  1a7v_A
3    A      91   H -1.700   1a7v     A  1a7v_A
4    D       3   H -1.360   1a7v     A  1a7v_A
..  ..     ...  ..    ...    ...   ...     ...
664  D     329   P -1.440   5jxb     A  5jxb_A
665  Y     429   H -2.990   5oaq     A  5oaq_A
666  R      39   K  0.413   5vp3     A  5vp3_A
667  S     128   G -0.378   5vp3     A  5vp3_A
668  V     183   T  0.354   5vp3     A  5vp3_A

[669 rows x 7 columns]

In [48]:
import pandas as pd
import os
from Bio.PDB import PDBParser

# 3문자 아미노산 코드를 1문자로 변환하는 사전
d3to1 = {
    'ALA': 'A', 'CYS': 'C', 'ASP': 'D', 'GLU': 'E', 'PHE': 'F',
    'GLY': 'G', 'HIS': 'H', 'ILE': 'I', 'LYS': 'K', 'LEU': 'L',
    'MET': 'M', 'ASN': 'N', 'PRO': 'P', 'GLN': 'Q', 'ARG': 'R',
    'SER': 'S', 'THR': 'T', 'VAL': 'V', 'TRP': 'W', 'TYR': 'Y'
}

def verify_pdb_residues(df, pdb_dir):
    parser = PDBParser(QUIET=True)
    check_results = []
    actual_res_list = []

    print("--- PDB WT 잔기 체크 시작 ---")
    
    for idx, row in df.iterrows():
        pdb_id = row['PDB_ID']
        chain_id = row['Chain']
        # PDB 포지션은 정수형으로 변환 (간혹 insertion code가 있는 경우 예외처리 필요)
        try:
            pos = int(row['MutPos'])
        except ValueError:
            check_results.append("Invalid Position Format")
            actual_res_list.append("N/A")
            continue

        expected_wt = row['WT']
        pdb_path = os.path.join(pdb_dir, f"{pdb_id}.pdb")

        # 1. 파일 존재 여부 확인
        if not os.path.exists(pdb_path):
            check_results.append("File Missing")
            actual_res_list.append("N/A")
            continue

        try:
            # 2. PDB 파싱
            structure = parser.get_structure(pdb_id, pdb_path)
            model = structure[0]
            
            # 3. 체인 및 잔기 접근
            if chain_id not in model:
                check_results.append(f"Chain {chain_id} Missing")
                actual_res_list.append("N/A")
                continue
                
            chain = model[chain_id]
            
            # PDB 잔기 ID 형식: ('hetero-flag', seq-number, 'insertion-code')
            # 일반적인 아미노산은 (' ', pos, ' ') 형태입니다.
            res_id = (' ', pos, ' ')
            
            if res_id in chain:
                residue = chain[res_id]
                res_name_3 = residue.get_resname()
                res_name_1 = d3to1.get(res_name_3, 'X') # 매핑 안되면 X
                
                actual_res_list.append(res_name_1)
                if res_name_1 == expected_wt:
                    check_results.append("Match")
                else:
                    check_results.append(f"Mismatch (Found: {res_name_1})")
            else:
                check_results.append("Position Missing in PDB")
                actual_res_list.append("N/A")

        except Exception as e:
            check_results.append(f"Error: {str(e)}")
            actual_res_list.append("N/A")

        if (idx + 1) % 50 == 0:
            print(f"진행 중... [{idx + 1}/{len(df)}]")

    # 결과 기록
    df['Actual_WT'] = actual_res_list
    df['Verify_Result'] = check_results
    return df

# --- 실행 부분 ---
# 사용자의 실제 경로 설정 (r을 붙여 raw string으로 처리)
pdb_dir_path = r"C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_Zenodo\pdbs"

# df_zenodo는 이미 로드되어 있다고 가정합니다.
df_verified = verify_pdb_residues(df_zenodo, pdb_dir_path)

# 결과 요약 출력
print("\n[ 검증 결과 요약 ]")
print(df_verified['Verify_Result'].value_counts())

# 불일치 항목만 따로 보기
mismatches = df_verified[df_verified['Verify_Result'].str.contains("Mismatch|Missing")]
if not mismatches.empty:
    print("\n[ 주의: 불일치 또는 누락된 항목 ]")
    print(mismatches[['PDB_ID', 'Chain', 'MutPos', 'WT', 'Actual_WT', 'Verify_Result']])

--- PDB WT 잔기 체크 시작 ---
진행 중... [50/669]
진행 중... [100/669]
진행 중... [150/669]
진행 중... [200/669]
진행 중... [250/669]
진행 중... [300/669]
진행 중... [350/669]
진행 중... [400/669]
진행 중... [450/669]
진행 중... [500/669]
진행 중... [550/669]
진행 중... [600/669]
진행 중... [650/669]

[ 검증 결과 요약 ]
Verify_Result
Match    669
Name: count, dtype: int64

In [67]:
import pandas as pd
import os
from Bio.PDB import PDBParser, PPBuilder

def generate_s669_fasta(df, pdb_dir, output_file):
    parser = PDBParser(QUIET=True)
    ppb = PPBuilder()
    
    # 중복된 PDB_ID와 Chain 조합 제거 (서열은 체인당 하나면 되므로)
    unique_targets = df[['PDB_ID', 'Chain']].drop_duplicates()
    
    print(f"--- FASTA 생성 시작 (대상: {len(unique_targets)}개 체인) ---")
    
    with open(output_file, 'w') as f:
        count = 0
        for _, row in unique_targets.iterrows():
            pdb_id = row['PDB_ID']
            chain_id = row['Chain']
            pdb_path = os.path.join(pdb_dir, f"{pdb_id}.pdb")
            
            if not os.path.exists(pdb_path):
                print(f"Warning: {pdb_id}.pdb 파일을 찾을 수 없습니다.")
                continue
                
            try:
                structure = parser.get_structure(pdb_id, pdb_path)
                model = structure[0]
                
                if chain_id in model:
                    # PPBuilder는 ATOM 레코드에서 연속된 폴리펩타이드를 찾아 서열로 변환합니다.
                    # 중간에 끊긴 루프가 있을 경우 여러 개의 조각(pp)이 나올 수 있어 합쳐줍니다.
                    chain_seq = ""
                    for pp in ppb.build_peptides(model[chain_id]):
                        chain_seq += str(pp.get_sequence())
                    
                    if chain_seq:
                        # 헤더 형식: >PDBID_Chain
                        f.write(f">{pdb_id}_{chain_id}\n")
                        f.write(f"{chain_seq}\n")
                        count += 1
                else:
                    print(f"Warning: {pdb_id}.pdb 내에 {chain_id} 체인이 없습니다.")
                    
            except Exception as e:
                print(f"Error processing {pdb_id}: {str(e)}")

    print(f"--- 완료! 총 {count}개의 서열이 {output_file}에 저장되었습니다. ---")

# --- 실행 부분 ---
df_zenodo = pd.read_csv(r"C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_zenodo.tsv", sep ="\t")
pdb_dir_path = r"C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_Zenodo\pdbs"
output_fasta = "S669_zenodo.fasta"

# 이전에 검증에 사용했던 df_zenodo를 그대로 사용합니다.
generate_s669_fasta(df_zenodo, pdb_dir_path, output_fasta)

--- FASTA 생성 시작 (대상: 94개 체인) ---
--- 완료! 총 94개의 서열이 S669_zenodo.fasta에 저장되었습니다. ---

In [72]:
import pandas as pd
import os
from Bio.PDB import PDBParser, PPBuilder

def generate_s669_fasta_with_pos(df, pdb_dir, output_file):
    parser = PDBParser(QUIET=True)
    ppb = PPBuilder()
    
    # 3문자 -> 1문자 변환용 (PPBuilder 내부에서 쓰이지만 매핑 확인용으로 선언)
    d3to1 = {'ALA': 'A', 'CYS': 'C', 'ASP': 'D', 'GLU': 'E', 'PHE': 'F', 'GLY': 'G', 'HIS': 'H', 
             'ILE': 'I', 'LYS': 'K', 'LEU': 'L', 'MET': 'M', 'ASN': 'N', 'PRO': 'P', 'GLN': 'Q', 
             'ARG': 'R', 'SER': 'S', 'THR': 'T', 'VAL': 'V', 'TRP': 'W', 'TYR': 'Y'}

    # 결과를 저장할 리스트 (나중에 df에 합침)
    seq_pos_list = [None] * len(df)
    
    # 유니크한 PDB-Chain 조합별로 처리
    unique_targets = df[['PDB_ID', 'Chain']].drop_duplicates()
    
    print(f"--- FASTA 생성 및 포지션 매핑 시작 ---")
    
    with open(output_file, 'w') as f_out:
        for _, target in unique_targets.iterrows():
            pdb_id, chain_id = target['PDB_ID'], target['Chain']
            pdb_path = os.path.join(pdb_dir, f"{pdb_id}.pdb")
            
            if not os.path.exists(pdb_path):
                continue
                
            try:
                structure = parser.get_structure(pdb_id, pdb_path)
                model = structure[0]
                if chain_id not in model: continue
                
                # 1. PPBuilder로 물리적으로 연결된 서열 조각(Polypeptides) 추출
                polypeptides = ppb.build_peptides(model[chain_id])
                
                full_seq = ""
                # FASTA 내 각 글자가 실제 PDB에서 몇 번이었는지 기록할 리스트
                pdb_res_nums = [] 

                for pp in polypeptides:
                    full_seq += str(pp.get_sequence())
                    # 각 잔기의 PDB 번호(id[1])를 순서대로 추출
                    for residue in pp:
                        pdb_res_nums.append(residue.get_id()[1])
                
                if not full_seq: continue

                # 2. FASTA 파일 쓰기
                f_out.write(f">{pdb_id}_{chain_id}\n{full_seq}\n")

                # 3. 해당 PDB_ID/Chain을 쓰는 모든 행(Mutation)에 대해 SeqPos 계산
                row_indices = df[(df['PDB_ID'] == pdb_id) & (df['Chain'] == chain_id)].index
                
                for idx in row_indices:
                    target_pdb_pos = int(df.at[idx, 'MutPos'])
                    
                    # PDB 번호 리스트에서 해당 번호가 몇 번째(index)에 있는지 찾기
                    try:
                        # 0-based index에 1을 더해 1-based position 생성
                        seq_index = pdb_res_nums.index(target_pdb_pos)
                        seq_pos_list[idx] = seq_index + 1 
                    except ValueError:
                        # PDB 구조에 좌표가 없는 번호인 경우
                        seq_pos_list[idx] = None
                        
            except Exception as e:
                print(f"Error in {pdb_id}_{chain_id}: {e}")

    # 4. 데이터프레임 업데이트
    df['SeqPos'] = seq_pos_list
    print(f"--- 완료! FASTA가 저장되었고 df_zenodo에 'SeqPos' 컬럼이 추가되었습니다. ---")
    return df

# --- 실행 부분 ---
df_zenodo = pd.read_csv(r"C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_zenodo.tsv", sep ="\t")
pdb_dir_path = r"C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_Zenodo\pdbs"
output_fasta = "S669_zenodo.fasta"

# 함수 실행 및 결과 업데이트
df_zenodo = generate_s669_fasta_with_pos(df_zenodo, pdb_dir_path, output_fasta)

# 결과 확인
print(df_zenodo[['PDB_ID', 'Chain', 'MutPos', 'SeqPos', 'WT']].head())

--- FASTA 생성 및 포지션 매핑 시작 ---
--- 완료! FASTA가 저장되었고 df_zenodo에 'SeqPos' 컬럼이 추가되었습니다. ---
  PDB_ID Chain  MutPos  SeqPos WT
0   1a0f     A      11      11  S
1   1a7v     A     104     104  A
2   1a7v     A      66      66  A
3   1a7v     A      91      91  A
4   1a7v     A       3       3  D

In [74]:
df_zenodo.to_csv("S669_zenodo.tsv", sep='\t', index=False)

In [76]:
df_zenodo

    WT  MutPos Mut    DDG PDB_ID Chain     Key  SeqPos
0    S      11   A -1.800   1a0f     A  1a0f_A      11
1    A     104   H -2.690   1a7v     A  1a7v_A     104
2    A      66   H -1.980   1a7v     A  1a7v_A      66
3    A      91   H -1.700   1a7v     A  1a7v_A      91
4    D       3   H -1.360   1a7v     A  1a7v_A       3
..  ..     ...  ..    ...    ...   ...     ...     ...
664  D     329   P -1.440   5jxb     A  5jxb_A      25
665  Y     429   H -2.990   5oaq     A  5oaq_A     199
666  R      39   K  0.413   5vp3     A  5vp3_A      39
667  S     128   G -0.378   5vp3     A  5vp3_A     128
668  V     183   T  0.354   5vp3     A  5vp3_A     183

[669 rows x 8 columns]

In [77]:
df_zenodo["FILE_PATH"] = df_zenodo["PDB_ID"] + ".pdb"

In [79]:
df_zenodo.to_csv("S669_zenodo.tsv", sep='\t', index=False)

In [80]:
df_zenodo

    WT  MutPos Mut    DDG PDB_ID Chain     Key  SeqPos FILE_PATH
0    S      11   A -1.800   1a0f     A  1a0f_A      11  1a0f.pdb
1    A     104   H -2.690   1a7v     A  1a7v_A     104  1a7v.pdb
2    A      66   H -1.980   1a7v     A  1a7v_A      66  1a7v.pdb
3    A      91   H -1.700   1a7v     A  1a7v_A      91  1a7v.pdb
4    D       3   H -1.360   1a7v     A  1a7v_A       3  1a7v.pdb
..  ..     ...  ..    ...    ...   ...     ...     ...       ...
664  D     329   P -1.440   5jxb     A  5jxb_A      25  5jxb.pdb
665  Y     429   H -2.990   5oaq     A  5oaq_A     199  5oaq.pdb
666  R      39   K  0.413   5vp3     A  5vp3_A      39  5vp3.pdb
667  S     128   G -0.378   5vp3     A  5vp3_A     128  5vp3.pdb
668  V     183   T  0.354   5vp3     A  5vp3_A     183  5vp3.pdb

[669 rows x 9 columns]

In [2]:
import pandas as pd

def analyze_pos_differences(df):
    # 1. 오프셋 계산 (PDB번호 - FASTA순서)
    # SeqPos가 NaN인 경우(구조에 좌표가 없는 경우)는 제외하고 계산합니다.
    df_valid = df.dropna(subset=['SeqPos']).copy()
    df_valid['Offset'] = df_valid['MutPos'].astype(int) - df_valid['SeqPos'].astype(int)

    # 2. Key 단위로 그룹화하여 통계 산출
    key_stats = df_valid.groupby('Key')['Offset'].agg(['min', 'max', 'mean', 'nunique', 'std']).reset_index()
    
    # 3. 결과 분석 및 카운팅
    # 오프셋이 일정한 그룹 (std == 0 또는 nunique == 1)
    consistent_keys = key_stats[key_stats['nunique'] == 1]
    
    # 오프셋이 상이한 그룹 (중간에 Gap이 있거나 구조가 끊긴 경우)
    inconsistent_keys = key_stats[key_stats['nunique'] > 1]
    
    # [추가] 오프셋이 0이 아닌 케이스 계산
    # 1) 일정한데 0이 아닌 경우 (단순 오프셋 존재)
    nonzero_consistent = consistent_keys[consistent_keys['min'] != 0]
    # 2) 일정하지 않은 경우 (Gap 존재 등, 당연히 0이 아님)
    nonzero_total_count = len(nonzero_consistent) + len(inconsistent_keys)
    # 3) 완벽하게 1:1 매칭되는 경우 (Offset이 0인 경우)
    perfect_match_count = len(consistent_keys[consistent_keys['min'] == 0])

    print(f" 전체 요약 ")
    print(f"- 분석 대상 Key 개수: {len(key_stats)}")
    print(f"- 오프셋이 0인 Key (완벽 일치): {perfect_match_count}")
    print(f"- 오프셋이 0이 아닌 Key (오프셋/Gap 존재): {nonzero_total_count}") # 요청하신 부분
    print(f"  └ 오프셋이 일정하나 0은 아님: {len(nonzero_consistent)}")
    print(f"  └ 오프셋이 불규칙함 (Gap 의심): {len(inconsistent_keys)}")
    print("-" * 30)

    if not inconsistent_keys.empty:
        print("\n[ 오프셋이 상이한 Key 리스트 (주의 필요) ]")
        print(inconsistent_keys.sort_values('std', ascending=False).head(10))
    
    if not nonzero_consistent.empty:
        print("\n[ 오프셋이 일정하지만 0은 아닌 Key 샘플 ]")
        print(nonzero_consistent[['Key', 'min']].rename(columns={'min': 'Constant_Offset'}).head(10))

    return key_stats, inconsistent_keys

# 실행 예시
df_zenodo = pd.read_csv(r"C:\Users\Kunny\Documents\GitHub\CAGI\EvoStructCLIP\S669\S669_zenodo.tsv", sep="\t")
key_summary, gap_keys = analyze_pos_differences(df_zenodo)

 전체 요약
- 분석 대상 Key 개수: 94
- 오프셋이 0인 Key (완벽 일치): 37
- 오프셋이 0이 아닌 Key (오프셋/Gap 존재): 57
  └ 오프셋이 일정하나 0은 아님: 54
  └ 오프셋이 불규칙함 (Gap 의심): 3
------------------------------

[ 오프셋이 상이한 Key 리스트 (주의 필요) ]
       Key  min  max       mean  nunique       std
81  3o39_A   28   34  32.000000        4  2.756810
42  1x0j_A   73   78  77.000000        3  1.914854
71  3c2i_A   91   92  91.416667        2  0.514929

[ 오프셋이 일정하지만 0은 아닌 Key 샘플 ]
       Key  Constant_Offset
2   1ba3_A                4
7   1dxx_A                8
8   1ekg_A               89
10  1fh5_H                3
12  1ft8_A              120
14  1g3p_A               26
15  1glu_A              433
16  1gua_B               55
18  1h0x_A                8
21  1ir3_A              983

In [6]:
df_zenodo[df_zenodo["Key"]=="1ba3_A"]

   WT  MutPos Mut    DDG PDB_ID Chain     Key  SeqPos FILE_PATH
14  H     461   D -1.745   1ba3     A  1ba3_A     457  1ba3.pdb
15  H     489   D  0.287   1ba3     A  1ba3_A     485  1ba3.pdb
16  H     489   K -0.287   1ba3     A  1ba3_A     485  1ba3.pdb
17  H     489   M -0.263   1ba3     A  1ba3_A     485  1ba3.pdb